com.syan.dev.fromgridcustom.element.pluginLabel=Form Grid Custom

#Form Grid
form.formgrid.fieldId=Field ID
form.formgrid.editFormGrid=Configure Form Grid
form.formgrid.id=ID
form.formgrid.invalidId=Only alpha-numeric and underscore characters allowed
form.formgrid.label=Label
form.formgrid.formId=Form
form.formgrid.columns=Columns
form.formgrid.columns.desc=Value should be mapped to Field ID of form. Please note that \u201cFile\u201d and \u201cImage\u201d format types require a form store (e.g. Multiple Form Row Data Store) that handles file storage.
form.formgrid.value=Value
form.formgrid.loadBinder=Load Data From
form.formgrid.storeBinder=Save Data To
form.formgrid.readonly=Readonly
form.formgrid.readonlyLabel=Display Field as Label When Readonly?
form.formgrid.disabledAdd=Disable Add Feature 
form.formgrid.disabledDelete=Disable Delete Feature
form.formgrid.deleteMessage=Delete confirmation message
form.formgrid.deleteMessage.value=Delete row?
form.formgrid.ui=UI
form.formgrid.enableSorting=Enable Sorting Feature
form.formgrid.submitButtonLabel.normal=Form Submit Button Label (Normal Mode)
form.formgrid.submitButtonLabel.readonly=Form Submit Button Label (Readonly Mode)
form.formgrid.addEntry=Add Entry
form.formgrid.sortField=Field ID for Sorting
form.formgrid.sortField.desc=Field ID is used to keep sorting data. Required when enable sorting feature.
form.formgrid.formatType=Format Type
form.formgrid.formatType.text=Text
form.formgrid.formatType.html=HTML
form.formgrid.formatType.decimal=Decimal
form.formgrid.formatType.currency=Currency
form.formgrid.formatType.date=Date
form.formgrid.formatType.file=File
form.formgrid.formatType.image=Image
form.formgrid.formatType.options=Options
form.formgrid.formatType.nl2br=Multiple Lines Text
form.formgrid.format=Format
form.formgrid.width=Width
form.formgrid.visibility=Visibility
form.formgrid.visibility.yes=Yes
form.formgrid.visibility.no=No
form.formgrid.validation=Validation
form.formgrid.validateMinRow=Min Number of Row Validation (Integer)
form.formgrid.validateMaxRow=Max Number of Row Validation (Integer)
form.formgrid.errorMessage=Error Message 
form.formgrid.invalidNumberOfRow=Invalid number of rows
form.formgrid.showRowNumber=Show Row Numbering?
form.formgrid.pageSize=Paging Size
form.formgrid.popupWindowHeight=Popup Dialog Height
form.formgrid.popupWindowWidth=Popup Dialog Width
form.formgrid.uniqueKey=Unique Column
form.formgrid.uniqueKey.error={0} column must has unique value!
form.formgrid.uniqueKey.desc=Optional column to check for duplicate rows
form.formgrid.validationAndData=Data & Validation
form.formgrid.sorting=Sorting
form.formgrid.form=Form
form.formgrid.grid=Grid
form.formgrid.dataBinder=Data Store
form.formgrid.validator=Validator
form.formGrid.data.deletion=Child Form Data Deletion Options
form.formGrid.data.deletion.desc=Please note that these options will be override if a higher level value is set.
form.formgrid.requestParam=URL Request Parameters for Popup Form
form.formgrid.editRow=Edit Row
form.formgrid.deleteRow=Delete Row
form.formgrid.moveUp=Move Up
form.formgrid.moveDown=Move Down
form.formgrid.bulkDeleteMessage=Are you sure you want to delete the selected rows?
form.formgrid.duplicate=Duplicate
form.formgrid.duplicateRow=Duplicate Row

#List Grid
form.listgrid.editListGrid=Configure List Grid
form.listgrid.id=ID
form.listgrid.invalidId=Only alpha-numeric and underscore characters allowed
form.listgrid.label=Label
form.listgrid.label.value=List Grid
form.listgrid.listId=List
form.listgrid.listId.desc=List to display for selection
form.listgrid.formId=Form to Edit Row
form.listgrid.formId.desc=Optional form to allow row editing
form.listgrid.insert=Insert
form.listgrid.addRows=Add Rows
form.listgrid.uniqueKey=Unique Column
form.listgrid.uniqueKey.desc=Optional column to check for duplicate rows
form.listgrid.columns=Columns
form.listgrid.columns.desc=Value should be mapped to Field ID of form. Please note that \u201cFile\u201d and \u201cImage\u201d format types require a form store store (e.g. Multiple Form Row Data Store) that handles file storage.
form.listgrid.value=Value
form.listgrid.chooseLoadBinder=Load Data From
form.listgrid.loadBinder=Load Data From
form.listgrid.chooseStoreBinder=Save Data To
form.listgrid.storeBinder=Save Data To
form.listgrid.readonly=Readonly
form.listgrid.readonlyLabel=Display Field as Label When Readonly?
form.listgrid.disabledAdd=Disable Add Feature 
form.listgrid.disabledDelete=Disable Delete Feature
form.listgrid.deleteMessage=Delete Confirmation Message
form.listgrid.ui=UI
form.listgrid.enableSorting=Enable Sorting Feature
form.listgrid.submitButtonLabel.normal=Form Submit Button Label (Normal Mode)
form.listgrid.submitButtonLabel.readonly=Form Submit Button Label (Readonly Mode)
form.listgrid.addEntry=Add Entry
form.listgrid.sortField=Field ID for Sorting
form.listgrid.sortField.desc=Field ID is used to keep sorting data. Required when enable sorting feature.
form.listgrid.formatType=Format Type
form.listgrid.formatType.text=Text
form.listgrid.formatType.html=HTML
form.listgrid.formatType.decimal=Decimal
form.listgrid.formatType.date=Date
form.listgrid.formatType.file=File
form.listgrid.formatType.image=Image
form.listgrid.formatType.options=Options
form.listgrid.format=Format
form.listgrid.editable=Editable
form.listgrid.editable.yes=Yes
form.listgrid.editable.no=No
form.listgrid.editable.tooltip=Click to Edit
form.listgrid.editable.ok=OK
form.listgrid.buttonLabel=Insert Button Label
form.listgrid.showRowNumber=Show Row Numbering?
form.listgrid.width=Width
form.listgrid.popupWindowHeight=Popup Dialog Height
form.listgrid.popupWindowWidth=Popup Dialog Width
form.listgrid.validation=Validation
form.listgrid.validateMinRow=Min Number of Row Validation (Integer)
form.listgrid.validateMaxRow=Max Number of Row Validation (Integer)
form.listgrid.errorMessage=Error Message 
form.listgrid.invalidNumberOfRow=Invalid number of rows
form.listgrid.sorting=Sorting
form.listgrid.data=Data
form.listgrid.validationAndData=Data & Validation
form.listgrid.grid=Grid
form.listgrid.form=Form
form.listgrid.list=List
form.listgrid.advanced=Advanced
form.listgrid.requestParam=URL Request Parameters for List
form.listgrid.Parameter=Parameter
form.listgrid.field=Field Id
form.listgrid.defaultValue=Default Value
form.listgrid.validator=Validator
form.listgrid.checkboxDisable=Disable Checkbox
form.listgrid.disabledDuplicate=Disable Duplicate
form.listgrid.showPopupDuplicate=Show popup when duplicate?

#FormRowDeleteDataListAction
datalist.formrowdeletedatalistaction.editDeleteAction=Configure Delete
datalist.formrowdeletedatalistaction.label=Label
datalist.formrowdeletedatalistaction.confirmationMessage=Confirmation Message
datalist.formrowdeletedatalistaction.formId=Form
datalist.formrowdeletedatalistaction.noform=Error! No form is set.
datalist.formrowdeletedatalistaction.error.delete=Error during deleting records.
datalist.formrowdeletedatalistaction.deleteGridData=Delete Associated Grid Data?
datalist.formrowdeletedatalistaction.deleteGridData.desc=If the record has grid element(s), this option will delete the inner grid data.
datalist.formrowdeletedatalistaction.deleteChildFormData=Delete Associated Child Form Data? 
datalist.formrowdeletedatalistaction.deleteChildFormData.desc=If the record has child element(s), this option will delete the child data. 
datalist.formrowdeletedatalistaction.abortRelatedRunningProcesses=Abort Related Running Processes? 
datalist.formrowdeletedatalistaction.abortRelatedRunningProcesses.desc=If checked, active process instance associated with the record ID will be aborted.
datalist.formrowdeletedatalistaction.deleteFiles=Delete Files?
datalist.formrowdeletedatalistaction.deleteFiles.desc=If the record contains file upload element, this option will delete the actual uploaded file(s).
datalist.formrowdeletedatalistaction.pleaseConfirm=Please Confirm?